### ISSUE TITLE
TitanDb Wrapper

### ISSUE THREAD

**Issue by elubow** [anvie/blueprints-scala#35]
Having spent the better part of 2 days trying to get Titan to work unsuccessfully, I was wondering if someone create a wiki page on how to do this with Titan for Scala `2.10`:

``` scala
  import com.ansvia.graph.BlueprintsWrapper._
  implicit val db = TinkerGraphFactory.createTinkerGraph()
  case class Person(name:String) extends DbObject
  val bob = Person("bob").save()
  val alice = Person("alice").save()
  alice --> "sendsPgpKeyTo" --> bob
```

**Comment by pdolega** [comment]
@elubow tests are written with use of in-memory Titan graph implementation. They work fine (well - they are run automatically on Travis with every change). 

Did you take a look at them ?

**Comment by elubow** [comment]
I did look at the tests and I can't seem to get the same thing working for Titan.

**Comment by pdolega** [comment]
What do you mean by: `... I can't seem to get the same thing working for Titan.`

These tests run on Titan specifically. What errors do you have ? Stack trace ?

**Comment by pdolega** [comment]
Hey @elubow did you figure out the solution for your problem ?

If there is nothing else to add here I guess you could close this issue @anvie

**Comment by anvie** [comment]
I close this issue, if problem occur please comment and I will reopen.
