### ISSUE TITLE
Question: Why store className (_class_) in the database ?

### ISSUE THREAD

**Issue by hajime-moto** [anvie/blueprints-scala#38]
I'm using OrientDB and when trying to save a record to the database with the following code a `_class_` property is added to the database for every record which stores the full className (`com.messaging.actor.Person`). I'm worried this tight coupling of the full className(including package name) will cause issues if someone moves the classes around.

```
val person = Person("John Smith")
    val address = new Address("Sydney, Australia")
    db.save(person)
    db.save(address)
    person --> "address is" --> address 
```

Is there a reason why storing the full className in the database was chosen ? Instead of just passing the Class to convert Vertex object to Case Class whenever needed (eg: toCC method) ? 

```
val vertices = db.getVertices("name", "John Smith").asScala
    vertices.foreach(vert => {
      println(vert.toCC[Person])
    })
```

**Comment by anvie** [comment]
Sometimes I need  to know which class is bound to the record.
